version: '3.8'
services:
  mysql:
    container_name: demo-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my-database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    container_name: demo-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
        - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  mysql_data:


